name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: oss-metrics
          auto-activate-base: false
          environment-file: environment.yaml

      - name: Install dev dependencies
        run: |
          conda env update --name oss-metrics --file environment_dev.yaml

      - name: Install project in editable mode
        run: |
          pip install -e .

      - name: Run tests
        run: |
          pytest -v
